### ISSUE TITLE
Missing README, LICENCE & EditorConfig

### ISSUE THREAD

**Issue by bobesa** [gezero/dovico#3]
Please add README file (https://help.github.com/articles/about-readmes/) to allow others to understand what this repository is actually for.

Please add LICENCE file (https://help.github.com/articles/licensing-a-repository/) to tell others if they can use it.

Please add EditorConfig configuration (https://github.com/editorconfig/editorconfig-core-js) to share formatting & other things with contributors.

**Comment by gezero** [comment]
I don't understand editor config, i share my config of my jetbrains products... Why would I have editor config?

**Comment by gezero** [comment]
Closing this issue because of no response...

**Comment by bobesa** [comment]
💩
